

POST http://localhost:5050/users/register
Content-Type: application/json

{
  "username": "chaan2",
  "name": "Charan Naik",
  "email": "chaa@gmail.com",
  "password": "Password@123"
}

###

POST http://localhost:5050/users/login
Content-Type: application/json

{
  "email": "chaa@gmail.com",
  "password": "Password@123"
}

###

GET http://localhost:5050/users/userprofdata
Content-Type: application/json

{
    "token": "21ddfc88f9537a95cbb48e85d188aba5e80b9c2c20d4506f274757e7a8fba640f2777429040888b895a9869324e4281f09122609c417eb09b6b65fbc10dd4904"
}





###
PUT http://localhost:5050/users/user_update

Content-Type: application/json

{

    "token": "becd6c2706dd52d036d6d346618d07a65cdc6e060d2e2b0616d650cd03ad6d2488953c45aa50936e54f31cf033e3861244398ffd8e41f5333afe585b7e54cc89",

    "bio": "Backend Developer",
    "currentPost": "Node.js Developer",
    "pastWork": [
        {
        "companyName": "Capgemini",
        "position": "Software Engineer",
        "startDate": "2023-02-15T00:00:00.000Z"
        }
    ],
    "education": [
        {
        "institutionName": "IIT Hyderabad",
        "degree": "M.Tech",
        "fieldOfStudy": "AI",
        "school": "Engineering"
        }
    ]
}
###
# PUT http://localhost:5050/users/user_update
# Content-Type: application/json
# Authorization: 1b4b0a6fbd31addbc0a953e891a436e113702a37b7c74298affc608ab298f45e5d6940d42c7424723888224788599ea6c27c76ee88d85d3659f430177723b828

# {
#     "bio": "Backend Developer",
#     "currentPost": "Node.js Developer",
#     "pastWork": [
#         {
#             "companyName": "Capgemini",
#             "position": "Software Engineer",
#             "startDate": "2023-02-15T00:00:00.000Z"
#         }
#     ],
#     "education": [
#         {
#             "institutionName": "IIT Hyderabad",
#             "degree": "M.Tech",
#             "fieldOfStudy": "AI",
#             "school": "Engineering"
#         }
#     ]
# }

###


GET http://localhost:5050/users/getallusers
Content-Type: application/json

### 

GET http://localhost:5050/users/updateUserProfileData
Content-Type: application/json
{
    "token": "becd6c2706dd52d036d6d346618d07a65cdc6e060d2e2b0616d650cd03ad6d2488953c45aa50936e54f31cf033e3861244398ffd8e41f5333afe585b7e54cc89"
}
    
###

GET  http://localhost:5050/users/downlodaresume?userId=69e286ef38d42e6742f4f653
Content-Type: application/json


###

POST  http://localhost:5050/users/sendConnectionRequest
Content-Type: application/json

{
    "token":"21ddfc88f9537a95cbb48e85d188aba5e80b9c2c20d4506f274757e7a8fba640f2777429040888b895a9869324e4281f09122609c417eb09b6b65fbc10dd4904"
}


###

GET http://localhost:5050/users/getAllRequset
Content-Type: application/json

{
    "token":"21ddfc88f9537a95cbb48e85d188aba5e80b9c2c20d4506f274757e7a8fba640f2777429040888b895a9869324e4281f09122609c417eb09b6b65fbc10dd4904"
}